version: "2"
services:  
    mongodb:
        image: mongo
        restart: always
        container_name: mongodb
        ports:
        - 27017:27017
        volumes:
        - ./data:/data/db
    unipilibrarysystem: 
      build: .
      restart: always
      command: python -u app.py
      container_name: unipi_LibrarySystem
      ports: 
        - "5000:5000"
      links:
        - mongodb
      depends_on:
        - mongodb
    